### ISSUE TITLE
Does not connect without -D PIO_FRAMEWORK_MBED_EVENTS_PRESENT

### ISSUE THREAD

**Issue by dtony** [maxgerhardt/pio-lorawan-example#2]
I compile this project using a Windows machine and I no longer have HardFault but the join procedure was simply not working (no error). I made it to work by adding 
`-D PIO_FRAMEWORK_MBED_EVENTS_PRESENT`
in platformio.ini 
I don't have my Linux machine available now to test if it works ok with it unfortunately.

**Comment by maxgerhardt** [comment]
Thank you, I haven't tested this with OTA but was sure it would work since it's just a copy.. Is now fixed.
